name: proverif

on:
  push:

jobs:
  proofs:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get update && sudo apt-get install -y opam libgtk2.0-dev
      - run: opam init
      - run: opam install -y proverif

      - name: hand-written proverif proofs
        run: |
          eval $(opam env)
          proverif -lib handwritten/cryptolib.pvl handwritten/spqr-cka.pv
          proverif -lib handwritten/cryptolib.pvl handwritten/spqr-dr.pv
        working-directory: ./proofs/proverif

      - name: extracted-model proverif proofs (reach + auth + conf, FS/PCS)
        run: |
          eval $(opam env)
          python3 hax.py verify-proverif epochs=2
